<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BLR2-5CG1327HQ2" failures="2" tests="13" name="Test" time="44.167" errors="0" timestamp="2023-06-03T15:32:44 IST">
  <testcase classname="TestCase.Register_Test" name="RegisterWithAllDetailsProperly" time="1.503"/>
  <testcase classname="TestCase.Register_Test" name="RegisterWithAllDetailsProperly" time="0.859"/>
  <testcase classname="TestCase.Register_Test" name="RegisterWithAllDetailsProperly" time="0.848"/>
  <testcase classname="TestCase.Register_Test" name="RegisterWithAllDetailsProperly" time="0.842"/>
  <testcase classname="TestCase.Register_Test" name="RegisterWithAllDetailsProperly" time="0.867"/>
  <testcase classname="TestCase.Register_Test" name="RegisterWithExistEmail" time="0.743"/>
  <testcase classname="TestCase.Register_Test" name="RegisterWithoutClickingPrivacy" time="0.727"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.555"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.625"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.594"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.627"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithInvalidCredential" time="0.531">
    <failure type="java.lang.AssertionError" message="Assertion Faile at void TestCase.Login_Test.verifyLoginWithInvalidCredential(java.lang.reflect.Method) expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assertion Faile at void TestCase.Login_Test.verifyLoginWithInvalidCredential(java.lang.reflect.Method) expected [true] but found [false]
at Utility.Utilise1.VerificationAssertion(Utilise1.java:67)
at TestCase.Login_Test.verifyLoginWithInvalidCredential(Login_Test.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidCredential -->
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithoutCredential" time="0.293">
    <failure type="java.lang.AssertionError" message="Assertion Faile at void TestCase.Login_Test.verifyLoginWithoutCredential(java.lang.reflect.Method) expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assertion Faile at void TestCase.Login_Test.verifyLoginWithoutCredential(java.lang.reflect.Method) expected [true] but found [false]
at Utility.Utilise1.VerificationAssertion(Utilise1.java:67)
at TestCase.Login_Test.verifyLoginWithoutCredential(Login_Test.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithoutCredential -->
</testsuite> <!-- Test -->
